# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Trusted Compute overlay for Traffic Intersection Agent services
# Included automatically when deploying with env ENABLE_TC=true

services:
  ovms-service:
    runtime: io.containerd.kata.v2
    healthcheck:
      start_period: 300s
    volumes:
      - ./tc-resolv.conf:/etc/resolv.conf:ro
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

networks:
  scenescape:
    ipam:
      config:
        - subnet: 172.20.0.0/16
