{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.openshell.enabled }}
{{- $metricsVars := include "stia.trafficAgent.metricsVars" . | fromJson -}}
apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: {{ include "stia.trafficAgent.fullname" . }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: traffic-agent
spec:
  podTemplate:
    {{- include "stia.trafficAgent.podTemplate" (merge (dict "root" .) $metricsVars) | nindent 4 }}
{{- end }}
